version: '3'

services: 
    client:
        container_name: blog-client
        build: ./client
        stdin_open: true
        ports: 
            - '3000:3000'
        depends_on: 
            - server
    server:
        container_name: blog-server
        restart: always
        build: .
        ports: 
            - '80:5000'
        depends_on: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'